# This file was generated by GoReleaser. DO NOT EDIT.
cask "nlit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7873bdfb7c26394e0ad4a62d4ef8a6f0f19902229ae8ed213677c394475a2f0e"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "148ba434b7c7c0e073b9582c837cf891751d6904a68769b19cbf8b4caf393243"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e320aec662f566376cee126ada4201d1730fec8064afc1dc5dbb939850c8e110"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b9745920065b1225615bc872650085f8a31af32b0ed7f04c62b1564464ef6b4"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nlit"
  desc "CLI for not-lost-in-translations — sync translations into your repo"
  homepage "https://github.com/makam92/not-lost-in-translations"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nlit"

  # No zap stanza required

end
