# This file was generated by GoReleaser. DO NOT EDIT.
cask "nlit" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "ae378e8cfa4ec6698abdd0789453190940e84d8acf6b1a6808a004f0476b5254"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "acdf65f392750b146ca17265166e347d65255525b5804f6ea051c6342adaff68"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17ef97e60a797b8a4efdf561a1b32e80d99877dbf0a564ad6be0bf708a27078d"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "953ff6ee5bf8e25580767be682de42ffea3903d7dc997612454a5794f3d1d7d9"
      url "https://github.com/nlit-app/homebrew-tap/releases/download/v#{version}/nlit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nlit"
  desc "CLI for not-lost-in-translations — sync translations into your repo"
  homepage "https://github.com/makam92/not-lost-in-translations"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nlit"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nlit"]
  end

  # No zap stanza required

end
