# This file was generated by GoReleaser. DO NOT EDIT.
cask "nlit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "48479e69b11135b28a857f5ac808fbc939751e3e87856fd2c4b11ecb5f98ef48"
      url "https://github.com/makam92/not-lost-in-translations/releases/download/v#{version}/nlit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0933c75b8432c9d940039ded8cad87791f94f334bb1a4fc2a980027b7fbf3b31"
      url "https://github.com/makam92/not-lost-in-translations/releases/download/v#{version}/nlit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "adcdf94f74074adde155967f40bb57fa4dce976469fb772a76d2708d2927d9a1"
      url "https://github.com/makam92/not-lost-in-translations/releases/download/v#{version}/nlit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "382c82c2f888a5f6663447b5b20be3fadc3d84962e7cf51df1448158a234235e"
      url "https://github.com/makam92/not-lost-in-translations/releases/download/v#{version}/nlit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nlit"
  desc "CLI for not-lost-in-translations — sync translations into your repo"
  homepage "https://github.com/makam92/not-lost-in-translations"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nlit"

  # No zap stanza required

end
